### ISSUE TITLE
AwsDnsManagement is not working after contains merge

### ISSUE THREAD

**Issue by hartmans** [Hadron/carthage_aws#7]
Take a look ath the warnings in https://github.com/Hadron/carthage_aws/runs/5604027669?check_suite_focus=true#step:4:95
It looks like the contains logic is not working correctly.

**Comment by srak289** [comment]
This is due to trimming the dot off the zone name here `dns.py : 74` `if self.name.endswith('.'): self.name = self.name[:-1]`.
Do you think it is important for AwsHostedZone to retain the trailing dot internally or should we always trim it?

If we should always trim the dot I'll submit a PR to close this issue with updated logic for `contains`.

**Comment by srak289** [comment]
#

**Comment by srak289** [comment]
Commit fd0d90b5e1ebf527f4a194cb1f48fff09bd03db2 (master) closes this issue.
